package ru.domeguard;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import java.util.*;
public final class DomeMenu implements Listener {private static final String TITLE="§5DomeGuard §8| §fНастройки";private static final String PLAYERS="§5DomeGuard §8| §fИммунитет";private final DomeGuardPlugin plugin;private final DomeManager dome;private final DamageManager damage;private final VoidManager vm;public DomeMenu(DomeGuardPlugin p,DomeManager d,DamageManager dm,VoidManager v){plugin=p;dome=d;damage=dm;vm=v;}
 private ItemStack item(Material m,String n,String... lore){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(n);x.setLore(Arrays.asList(lore));i.setItemMeta(x);return i;}
 public void open(Player p){Inventory i=Bukkit.createInventory(null,36,TITLE);i.setItem(10,item(Material.COMPASS,"§bЦентр", "§7X: "+dome.getCenterX(),"§7Z: "+dome.getCenterZ(),"§7Мир: "+dome.getWorldName()));i.setItem(11,item(Material.ENDER_PEARL,"§dРадиус X","§7ЛКМ: +10","§7ПКМ: -10","§7Сейчас: "+dome.getRadiusX()));i.setItem(12,item(Material.ENDER_EYE,"§dРадиус Z","§7ЛКМ: +10","§7ПКМ: -10","§7Сейчас: "+dome.getRadiusZ()));i.setItem(13,item(Material.SPYGLASS,"§aВерхняя граница","§7ЛКМ: +10","§7ПКМ: -10","§7Сейчас: "+dome.getMaxY()));i.setItem(14,item(Material.BEDROCK,"§cНижняя граница","§7ЛКМ: +10","§7ПКМ: -10","§7Сейчас: "+dome.getMinY()));i.setItem(21,item(Material.PLAYER_HEAD,"§bИммунитет к урону","§7Выбрать игроков","§7Иммунных: "+damage.getDamageImmuneCount()));i.setItem(24,item(Material.ENDER_CHEST,"§5Void Незера", "§7Включён: "+vm.enabled(),"§7Нажми для переключения"));p.openInventory(i);}
 private void players(Player p){Inventory i=Bukkit.createInventory(null,54,PLAYERS);int s=0;for(Player q:Bukkit.getOnlinePlayers()){if(s>=45)break;i.setItem(s++,head(q,damage.isDamageImmune(q.getUniqueId())));}i.setItem(49,item(Material.ARROW,"§eНазад"));p.openInventory(i);}
 private ItemStack head(Player p,boolean immune){ItemStack i=new ItemStack(Material.PLAYER_HEAD);var m=(org.bukkit.inventory.meta.SkullMeta)i.getItemMeta();m.setOwningPlayer(p);m.setDisplayName((immune?"§a":"§c")+p.getName());m.setLore(List.of(immune?"§aУрон отключён":"§cУрон включён","§7Нажми для переключения"));i.setItemMeta(m);return i;}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;String t=e.getView().getTitle();if(!t.equals(TITLE)&&!t.equals(PLAYERS))return;e.setCancelled(true);if(!p.hasPermission("dome.admin"))return;int s=e.getRawSlot();if(t.equals(PLAYERS)){if(s==49){open(p);return;}ItemStack it=e.getCurrentItem();if(it==null||it.getType()!=Material.PLAYER_HEAD)return;String n=ChatColor.stripColor(it.getItemMeta().getDisplayName());Player q=Bukkit.getPlayerExact(n);if(q!=null){damage.toggleDamageImmunity(q.getUniqueId());players(p);}return;}switch(s){case 11->dome.setRadiusX(e.isLeftClick()?dome.getRadiusX()+10:dome.getRadiusX()-10);case 12->dome.setRadiusZ(e.isLeftClick()?dome.getRadiusZ()+10:dome.getRadiusZ()-10);case 13->dome.setMaxY(e.isLeftClick()?dome.getMaxY()+10:dome.getMaxY()-10);case 14->dome.setMinY(e.isLeftClick()?dome.getMinY()+10:dome.getMinY()-10);case 21->players(p);case 24->vm.toggle();default->{} }if(s!=21)open(p);}
}
